---
title: "material template example"
output:
  rmdformats::material:
    highlight: kate
    self_contained: true
    code_folding: show
    thumbnails: true
    gallery: true
    fig_width: 4
    fig_height: 4
    df_print: kable
pkgdown:
  as_is: true    
---



```{r, results="asis", echo=FALSE, message=FALSE, warning=FALSE}
res <- knitr::knit_child('_example_body.Rmd', quiet = TRUE)
cat(res, sep = '\n')
```



# Tabbed sections

Here we test if tabbed sections work correctly.

## Classical tabs {.tabset}

classical tabs without fading effect.

### First tab

Quisquam sunt fugit sed aut quis et rerum mollitia. Qui consectetur eius autem ut assumenda alias. Repudiandae aut deleniti quod saepe nihil ratione alias laborum. Quibusdam aspernatur autem omnis voluptatum. Delectus illo non aut. Perferendis sunt facilis sed quam velit.
Veniam voluptates ut adipisci vel debitis deserunt rerum exercitationem. Accusamus quod eius occaecati voluptatem. Ut et qui veritatis. Nulla non eum id consectetur autem pariatur. Labore aperiam officiis molestiae sed ut perferendis ea. Aperiam aut ratione autem dolorem.
Fuga reprehenderit tempora ut ipsam cumque officiis dolorum. Sapiente omnis rerum sint quibusdam et delectus ratione. Molestiae praesentium rerum debitis deleniti voluptates enim.
Nihil aperiam velit provident accusamus suscipit voluptates. Aut sequi id debitis tempore. Qui atque quas sed illum officia maiores incidunt.
Similique maxime aliquam corrupti aut provident eaque. Laudantium placeat cupiditate pariatur dolore perspiciatis expedita impedit nobis. Quaerat non temporibus tempora provident eligendi.

### Second tab

Cum eaque dicta architecto culpa eius. Dignissimos officiis error exercitationem. Adipisci odit ad ea iusto fugiat laborum maiores. Dolore sunt et veritatis alias nesciunt maxime cumque. Culpa aut non ea. Culpa ex quia debitis sint eveniet cum.
Non eos ex aperiam dolor hic. Consectetur delectus placeat rerum consequuntur ducimus sed fugiat non. Aut voluptatem et et. Omnis sunt veniam omnis ullam.
Dolorem eius perspiciatis et veniam hic reprehenderit ipsam ut. Exercitationem rem eius quo. Nemo quis in voluptatibus ex.
Aut nihil quo iure quia. Error quam quidem inventore. Aut est est aut atque ipsum aut repellat. Eligendi delectus aut et quia voluptas dolores. Perspiciatis et reiciendis deleniti harum nihil officiis aperiam.
Laborum necessitatibus beatae modi aut illo. Quaerat esse eum ipsa quisquam totam. Vitae nesciunt excepturi voluptate iusto molestiae qui animi corrupti. Voluptates et illum quia.


## Pill tabs {.tabset .tabset-fade .tabset-pills}

Pill tabs with fading effect.

### First tab

Quisquam sunt fugit sed aut quis et rerum mollitia. Qui consectetur eius autem ut assumenda alias. Repudiandae aut deleniti quod saepe nihil ratione alias laborum. Quibusdam aspernatur autem omnis voluptatum. Delectus illo non aut. Perferendis sunt facilis sed quam velit.
Veniam voluptates ut adipisci vel debitis deserunt rerum exercitationem. Accusamus quod eius occaecati voluptatem. Ut et qui veritatis. Nulla non eum id consectetur autem pariatur. Labore aperiam officiis molestiae sed ut perferendis ea. Aperiam aut ratione autem dolorem.
Fuga reprehenderit tempora ut ipsam cumque officiis dolorum. Sapiente omnis rerum sint quibusdam et delectus ratione. Molestiae praesentium rerum debitis deleniti voluptates enim.
Nihil aperiam velit provident accusamus suscipit voluptates. Aut sequi id debitis tempore. Qui atque quas sed illum officia maiores incidunt.
Similique maxime aliquam corrupti aut provident eaque. Laudantium placeat cupiditate pariatur dolore perspiciatis expedita impedit nobis. Quaerat non temporibus tempora provident eligendi.

### Second tab

Cum eaque dicta architecto culpa eius. Dignissimos officiis error exercitationem. Adipisci odit ad ea iusto fugiat laborum maiores. Dolore sunt et veritatis alias nesciunt maxime cumque. Culpa aut non ea. Culpa ex quia debitis sint eveniet cum.
Non eos ex aperiam dolor hic. Consectetur delectus placeat rerum consequuntur ducimus sed fugiat non. Aut voluptatem et et. Omnis sunt veniam omnis ullam.
Dolorem eius perspiciatis et veniam hic reprehenderit ipsam ut. Exercitationem rem eius quo. Nemo quis in voluptatibus ex.
Aut nihil quo iure quia. Error quam quidem inventore. Aut est est aut atque ipsum aut repellat. Eligendi delectus aut et quia voluptas dolores. Perspiciatis et reiciendis deleniti harum nihil officiis aperiam.
Laborum necessitatibus beatae modi aut illo. Quaerat esse eum ipsa quisquam totam. Vitae nesciunt excepturi voluptate iusto molestiae qui animi corrupti. Voluptates et illum quia.
