---
title: "Sample rmarkdown document"
---


```{r knitr_init, echo=FALSE, results="asis", cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print = "75")
opts_chunk$set(echo = FALSE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
opts_knit$set(width = 75)
```

# Code and tables

## Syntax highlighting

Here is a sample code chunk, just to show that syntax highlighting works as expected.

```{r sh, echo=TRUE, eval=TRUE}
not_null <- function (v) {
  if (!is.null(v)) return(paste(v, "not null"))
}
```


## Verbatim

Here is the structure of the `iris` dataset.

```{r iris_str, echo=TRUE}
str(iris)
```

## Table

Here is a sample table output.

```{r iris_table}

x <- cut(iris$Sepal.Width, 4)
y <- cut(iris$Sepal.Length, 3)
tab <- table(x, y)
kable(tab)

```

Here we display a crosstab displayed in several different ways with a "pills"
interface. To do this, just pass your `table()` result to the `pilltabs()`
function.

```{r iris_pilltabs, results="asis"}

iris$seplc <- cut(iris$Sepal.Length,3)
tab <- table(iris$Species, iris$seplc)
pilltabs(tab)

```


